binance-exchange/binance-java-api

src/main/java/com/binance/api/client/domain/TimeInForce.java

FOK for the TimeInForce enum was missing. It was available in the official rest API docs. 
This patch adds it.

Fix missing Fill or Kill in TimeInForce

---

src/main/java/com/binance/api/client/domain/event/CandlestickEvent.java
src/main/java/com/binance/api/client/domain/event/CandlestickEventSerializer.java
src/main/java/com/binance/api/client/domain/market/OrderBookEntry.java
src/main/java/com/binance/api/client/domain/market/OrderBookEntrySerializer.java

This is used to make the events serializable which is desired if a user wants to dump the events on disk to analyze them later.

Add Json Serializers for CandlestickEvent and OrderBookEntry

---

src/main/java/com/binance/api/client/domain/event/UserDataUpdateEventDeserializer.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketListener.java

Resolves #29
Normally, you would only use a single Jackson ObjectMapper per the entire app, injected via DI or any other means. 
However, after looking at the current code, there's no way to delegate ObjectMapper construction in UserDataUpdateEventDeserializer.
Hence for this edge case, it is created lazily on first access instead of recreating it each time on deserialization.

fix-objectmapper

---

src/main/java/com/binance/api/client/domain/event/DepthEvent.java
src/test/java/com/binance/api/examples/DepthCacheExample.java

Hey,
Looking at the docs, it looks like its not possible to maintain a valid cache of open orders without back the 'U' and 'u' field on the Depth event, but only one was exposed. This PR exposes the other. I've left the old accessors in there for backwards compatibility, or they could be removed...
BTW - the example the `DepthCacheExample` does not subscribe to changes via the WS api before getting a snapshot from the rest API, which is what is recommended by your docs.
Also, if you run the example, you'll notice that the number of bid and ask orders increases over time and sometimes drops below the original snapshot size.  I would of expected a consistent cache size after each update. Not sure if there is something that can be done to avoid this? 
Thanks!
Andy

Expose the 'U' (first update), as well as the 'u' (final update) on Depth Event

---

src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java

OkHTTP3 limits the amount of connections to the same host to 5. This means you cannot open more than 5 steams of events. Truly undesirable within this context. I increased the amount to 100, for ease of use.
Having it on the default of 5, just causes you to be able to open websockets, but they wont provide you with any data. We tested this, and this fix resolves the issue.

Allow up to 100 connections to binance.

---

src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java
src/main/java/com/binance/api/client/security/AuthenticationInterceptor.java
src/test/java/com/binance/api/client/impl/BinanceApiServiceGeneratorTest.java

Issue #54 sees client applications eventually failing with a `StackOverflowException`.
This is caused by repeatedly call creating new clients, (i.e. rest or ws), rather than caching.
Each time a new client is created this code is invoked (from https://github.com/binance-exchange/binance-java-api/blob/master/src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java#L38):
```java
public static <S> S createService(Class<S> serviceClass, String apiKey, String secret) {
if (!StringUtils.isEmpty(apiKey) && !StringUtils.isEmpty(secret)) {
AuthenticationInterceptor interceptor = new AuthenticationInterceptor(apiKey, secret);
if (!httpClient.interceptors().contains(interceptor)) {
httpClient.addInterceptor(interceptor);
builder.client(httpClient.build());
retrofit = …
```

Fix for issue #54

---

README.md
src/main/java/com/binance/api/client/BinanceApiCallback.java
src/main/java/com/binance/api/client/BinanceApiWebSocketClient.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketListener.java

This PR should hopefully improve the error handling in the client and allow users to shutdown the client and/or a active web socket.
- Optional `onFailure` added to `BinanceApiCallback` to allow user to opt-in to receiving failure info, (Note: the interfacer remains a functional one for simple use-cases, it just now also supports error handling for when you care about such things).
- `BinanceApiWebSocketClient` enhanced to return `Closeable`s from calls creating web sockets, so that said web sockets can be later closed, if needed.
- `BinanceApiWebSocketClient` enhanced to be `Closeable` itself, closing the internal OKHttp dispatcher.
- `BinanceApiWebSocketListener` no longer throws an exception from `onFailure`, as this was just being thrown up the stack to the …

Error handling and shutdown improvements

---

src/main/java/com/binance/api/client/BinanceApiRestClient.java
src/main/java/com/binance/api/client/domain/general/AllAssets.java
src/main/java/com/binance/api/client/impl/BinanceApiAsyncRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiService.java

Although not a part of the official API, the getAllAsset page on
Binance’s website is useful for determining whether an asset can be
withdrawn.

Add support for AllAssets

---

README.md
src/main/java/com/binance/api/client/domain/account/NewOrder.java
src/main/java/com/binance/api/client/domain/account/NewOrderResponse.java
src/main/java/com/binance/api/client/domain/account/NewOrderResponseType.java
src/main/java/com/binance/api/client/domain/account/Trade.java
src/main/java/com/binance/api/client/impl/BinanceApiAsyncRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiCallbackAdapter.java
src/main/java/com/binance/api/client/impl/BinanceApiRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiService.java
src/test/java/com/binance/api/examples/OrdersExample.java

Thanks for this library! I'm currently using it in my Scala project and I want to share some improvements.
Binance added [`newOrderRespType`](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade) on their V3 API, allowing API clients to specify the desired response format by choosing between `ACK`/`RESULT`/`FULL`. `FULL` makes Binance return full details on the newly created order, including `executedQty` and `fills`, which in turn contain `price`, `qty` and `commission`. This enables you to **calculate the (average) fill price for market orders**. (fixes #105)
`binance-java-api` did not support this functionality yet. I also added error routing to `BinanceApiCallbackAdapter`, which previously threw any exceptions rather than calling …

Support newOrderRespType and fix onFailure routing in BinanceApiCallbackAdapter

---

src/main/java/com/binance/api/client/domain/account/Trade.java

Solves the issue #157 by adding the field in the response to the Trade object.

Issue 157: Exception when getting all trades of a symbol

---

README.md
src/main/java/com/binance/api/client/BinanceApiWebSocketClient.java
src/main/java/com/binance/api/client/domain/event/OrderTradeUpdateEvent.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java
src/test/java/com/binance/api/domain/event/UserDataUpdateEventDeserializerTest.java

This PR enables multi-symbol subscription per single (physical) websocket.
However, implementation does not permit cross-channel subscribing for the sake of backward compability.
Scope of PR:
- java code
- README.md documenting the changes (and reference on upper/lower case symbol difference between WS and REST so future API users don't go loco)
/ Miron

multi-channel subscription on single websocket

---

src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java

Since commit https://github.com/binance-exchange/binance-java-api/pull/133/commits/bed23c0e95d0c009bbf36486a4259420856f593c
there is only one application wide shared HTTP client instance. 
Because of the fact that no custom dispatcher for this client is configured, the following [default request limits](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Dispatcher.java#L40-L41) apply to the whole application:
```
private int maxRequests = 64;
private int maxRequestsPerHost = 5;
```
These limits are far to little when running a bigger trading application which retrieves updates for many symbols in parallel. 
To solve this issue I introduced a customized dispatcher with maxRequests and maxRequestsPerHost of 500.

custom dispatcher for sharedClient to allow for more parallel requests

---

src/main/java/com/binance/api/client/domain/event/AllMarketTickersEvent.java

Just adding bid price and quantity fields that were missing. 
Followed official docs (https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md) for reference.

Add bid price and quantity to AllMarketTickersEvent

---

src/main/java/com/binance/api/client/domain/account/request/CancelOrderResponse.java

This makes cancels easier to handle

 add status and executedQty to CancelOrderResponse

---

src/main/java/com/binance/api/client/domain/account/Order.java

`cummulativeQuoteQty` is needed to calculate the average price, for example when using market order
Reference: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data

Add Cummulative Quote Quantity

---

pom.xml

License metadata is useful for
http://www.mojohaus.org/license-maven-plugin/ interoperability as well
as a requirement of eventual listing in Maven Central (OSSHR) as per
https://central.sonatype.org/pages/requirements.html.

Add license to POM for license-maven-plugin compatibility

---

src/main/java/com/binance/api/client/BinanceApiAsyncRestClient.java
src/main/java/com/binance/api/client/BinanceApiRestClient.java
src/main/java/com/binance/api/client/BinanceApiWebSocketClient.java

This pull request replaces symbol `ç` to `c`. Because with symbol `ç` build will crash on some linux OSes.

Replace symbol `ç` to `c`

---

src/main/java/com/binance/api/client/config/BinanceApiConfig.java
src/main/java/com/binance/api/client/constant/BinanceApiConstants.java
src/main/java/com/binance/api/client/impl/BinanceApiAsyncRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java

This is a simple change to allow the user to override the base domain of the API URLs. I specifically restricted the changes to be a simple as possible so as to not redesign how things are configured currently.

Allow a custom base domain name so binance.us can be used

---

src/main/java/com/binance/api/client/BinanceApiWebSocketClient.java
src/main/java/com/binance/api/client/domain/event/BookTickerEvent.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java

- Add the _onBookTickerEvent_ WebSocket to BinanceApiWebSocketClient, for stream _'best price/qty on the order book for a symbol or symbols'._ consider the endpoint `[GET /api/v3/ticker/bookTicker](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)`
- Remove some un-used imports.
- src/main/java/com/binance/api/client/domain/event/BookTickerEvent.java
- src/main/java/com/binance/api/client/BinanceApiWebSocketClient.java
- src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java
1. Implementing a new BinanceApiWebSocketClient.onBookTickerEvent
Implements the best price/qty on the order book for a symbol or symbols' websoccket.

Add WebSocket BookTickerEvent

---

src/main/java/com/binance/api/client/BinanceApiAsyncMarginRestClient.java
src/main/java/com/binance/api/client/BinanceApiMarginRestClient.java
src/main/java/com/binance/api/client/domain/account/MarginNewOrder.java
src/main/java/com/binance/api/client/domain/account/MarginNewOrderResponse.java
src/main/java/com/binance/api/client/domain/account/SideEffectType.java
src/main/java/com/binance/api/client/impl/BinanceApiAsyncMarginRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiMarginRestClientImpl.java
src/main/java/com/binance/api/client/impl/BinanceApiService.java
src/test/java/com/binance/api/examples/MarginOrdersExample.java
src/test/java/com/binance/api/examples/MarginOrdersExampleAsync.java

- Create separate classes for MarginNewOrder and MarginNewOrderResponse
- Add SideEffectType to MarginNewOrder
- Refactor some code.
- src/main/java/com/binance/api/client/domain/account/SideEffectType.java
- src/main/java/com/binance/api/client/domain/account/MarginNewOrder.java
- src/main/java/com/binance/api/client/domain/account/MarginNewOrderResponse.java 
- src/main/java/com/binance/api/client/impl/BinanceApiService.java
- src/main/java/com/binance/api/client/impl/BinanceApiMarginRestClientImpl.java
- src/main/java/com/binance/api/client/impl/BinanceApiAsyncMarginRestClientImpl.java
- Placing a new margin order BinanceApiMarginRestClient.newOrder
The reason I went with separate classes for MarginNewOrder and MarginNewOrderResponse is because adding the new properties to NewOrder and …

Add side-effect type to the margin new order

---

pom.xml
src/main/java/com/binance/api/client/config/BinanceApiConfig.java
src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java
src/main/java/com/binance/api/client/impl/BinanceApiWebSocketClientImpl.java

#379 shows that the current codebase was never tested with testnet streaming api, this is a quick fix. my repo also was subject to maven-latest-revisions plugin, those look helpful going forward, or at least mostly harmless.

fixed the ability to do testnet streaming per #379

---

src/main/java/com/binance/api/client/domain/general/RateLimitType.java

* Cannot deserialize value of type `com.binance.api.client.domain.general.RateLimitType` from String "RAW_REQUESTS": not one of the values accepted for Enum class: [REQUEST_WEIGHT, ORDERS]

Fix deserialization issue for RateLimitType

---

src/main/java/com/binance/api/client/domain/event/UserDataUpdateEvent.java
src/main/java/com/binance/api/client/domain/event/UserDataUpdateEventDeserializer.java
src/test/java/com/binance/api/examples/AccountBalanceCacheExample.java
src/test/java/com/binance/api/examples/MarginUserDataStreamExample.java
src/test/java/com/binance/api/examples/UserDataStreamExample.java

The enum itself is left in place for backwards compatibility. This is a follow up to #386 in response to @brintal.

Fix examples now too. Deprecated the usage of the old naming. 
